spring:
  application:
    name: scanly
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${SCANLY_DATABASE_URL}
    username: ${SCANLY_DATABASE_USERNAME}
    password: ${SCANLY_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SCANLY_MAILSENDER_API_KEY}
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true
  thymeleaf:
    prefix: classpath:/email/templates/

crypto:
  key-source-type: ${SCANLY_KEY_SOURCE_TYPE}
  public-key-source: ${SCANLY_PUBLIC_KEY_PATH}
  private-key-source: ${SCANLY_PRIVATE_KEY_PATH}
  hash-algorithm: SHA-256

jwt:
  default-time-to-live: 30s
  max-time-to-live: 24h
  issuer: https://scanly.com
  mandatory-claims: exp, iat, iss, jti
  supported-algorithms: ES256

password:
  minimum-length: 8
  maximum-length: 20
  special-characters-required: true

mail:
  from: ${SCANLY_MAILSENDER_FROM_ADDRESS}