spring:
  application:
    name: scanly

crypto:
  key-source-type: ${SCANLY_KEY_SOURCE_TYPE}
  public-key-source: ${SCANLY_PUBLIC_KEY_PATH}
  private-key-source: ${SCANLY_PRIVATE_KEY_PATH}
  hash-algorithm: SHA-256

jwt:
  default-time-to-live: 30s
  max-time-to-live: 24h
  issuer: https://scanly.com
  mandatory-claims: exp, iat, iss, jti
  supported-algorithms: ES256
