package com.scanly.iam.user.persistence;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.Optional;
import java.util.UUID;

/**
 * Repository interface for {@link UserEntity} persistence operations.
 * <p>
 * This interface provides standard CRUD functionality via {@link JpaRepository}
 * and includes optimized native queries for identity management operations.
 * It interfaces directly with the {@code iam.users} schema.
 */
public interface UserRepository extends JpaRepository<UserEntity, UUID> {

    /**
     * Performs a low-level native insertion of a new user by email.
     * <p>
     * This method bypasses the standard JPA lifecycle for maximum efficiency
     * during high-volume registration events. It utilizes the PostgreSQL
     * {@code RETURNING} clause to immediately retrieve the generated
     * {@code user_id} without requiring a second SELECT query.
     *
     * @param email The unique email address to associate with the new user record.
     * @return The {@link UUID} of the newly created user, generated by the database.
     */
    @Query(
            value =
                """
                    INSERT INTO iam.users (email)
                    VALUES (:email)
                    RETURNING user_id
                """,
            nativeQuery = true
    )
    UUID insertUser(@Param("email") String email);

    Optional<UserEntity> findByEmail(String email);
}