package com.scanly.crypto.api;

import com.scanly.security.token.jwt.decoding.api.JwtDecoder;

/**
 * Interface for verifying digital signatures to ensure data integrity
 * and authenticity.
 * <p>
 * In the Scanly ecosystem, the Verifier is a lower level engine that will
 * execute the cryptographic math to validate tokens generated by a protected
 * {@link Signer}. Typically, this will be used by services like {@link JwtDecoder}
 * that leverages the crypto package for lower level maths.
 * </p>
 */
public interface Verifier {
    /**
     * Verifies that a digital signature is valid for the given data
     * using the public key associated with the provided Key ID.
     *
     * @param kid       The unique identifier for the public key to be used.
     * @param data      The original raw data that was supposedly signed.
     * @param signature The digital signature to be validated.
     * @return {@code true} if the signature is valid; {@code false} otherwise.
     */
    boolean verify(String kid, byte[] data, byte[] signature);
}